name: NET build
on:
  workflow_call:
    inputs:
      dotnet-version:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
      - name: Package
        run: dotnet pack

